CREATE TABLE public.site_survey_templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  active boolean NOT NULL DEFAULT true,
  created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (name)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.site_survey_templates TO authenticated;
GRANT ALL ON public.site_survey_templates TO service_role;
ALTER TABLE public.site_survey_templates ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.site_survey_sections (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  template_id uuid NOT NULL REFERENCES public.site_survey_templates(id) ON DELETE CASCADE,
  title text NOT NULL,
  description text,
  position integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.site_survey_sections TO authenticated;
GRANT ALL ON public.site_survey_sections TO service_role;
ALTER TABLE public.site_survey_sections ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.site_survey_questions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  section_id uuid NOT NULL REFERENCES public.site_survey_sections(id) ON DELETE CASCADE,
  prompt text NOT NULL,
  question_type text NOT NULL DEFAULT 'checkbox' CHECK (question_type IN ('checkbox','text','textarea','number','select')),
  required boolean NOT NULL DEFAULT false,
  options jsonb NOT NULL DEFAULT '[]'::jsonb,
  position integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.site_survey_questions TO authenticated;
GRANT ALL ON public.site_survey_questions TO service_role;
ALTER TABLE public.site_survey_questions ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.site_survey_visits (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  survey_number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  template_id uuid REFERENCES public.site_survey_templates(id) ON DELETE SET NULL,
  client_id uuid REFERENCES public.clients(id) ON DELETE RESTRICT,
  client_unit_id uuid REFERENCES public.client_units(id) ON DELETE RESTRICT,
  project_id uuid REFERENCES public.projects(id) ON DELETE RESTRICT,
  technician_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  created_by uuid NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  status text NOT NULL DEFAULT 'agendada' CHECK (status IN ('agendada','em_andamento','em_revisao','concluida','cancelada')),
  scheduled_start timestamptz NOT NULL,
  scheduled_end timestamptz,
  address text NOT NULL,
  contact_name text,
  contact_phone text,
  notes text,
  review_notes text,
  started_at timestamptz,
  submitted_at timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (client_id IS NOT NULL OR project_id IS NOT NULL),
  CHECK (scheduled_end IS NULL OR scheduled_end >= scheduled_start)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.site_survey_visits TO authenticated;
GRANT ALL ON public.site_survey_visits TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.site_survey_visits_survey_number_seq TO authenticated, service_role;
ALTER TABLE public.site_survey_visits ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.site_survey_responses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  visit_id uuid NOT NULL REFERENCES public.site_survey_visits(id) ON DELETE CASCADE,
  question_id uuid NOT NULL REFERENCES public.site_survey_questions(id) ON DELETE RESTRICT,
  answer jsonb NOT NULL DEFAULT 'null'::jsonb,
  answered_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  answered_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (visit_id, question_id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.site_survey_responses TO authenticated;
GRANT ALL ON public.site_survey_responses TO service_role;
ALTER TABLE public.site_survey_responses ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.site_survey_attachments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  visit_id uuid NOT NULL REFERENCES public.site_survey_visits(id) ON DELETE CASCADE,
  question_id uuid REFERENCES public.site_survey_questions(id) ON DELETE SET NULL,
  uploaded_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  file_name text NOT NULL,
  storage_path text NOT NULL UNIQUE,
  content_type text,
  file_size bigint NOT NULL DEFAULT 0 CHECK (file_size >= 0),
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.site_survey_attachments TO authenticated;
GRANT ALL ON public.site_survey_attachments TO service_role;
ALTER TABLE public.site_survey_attachments ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.site_survey_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  visit_id uuid NOT NULL REFERENCES public.site_survey_visits(id) ON DELETE CASCADE,
  actor_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  action text NOT NULL,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.site_survey_logs TO authenticated;
GRANT ALL ON public.site_survey_logs TO service_role;
ALTER TABLE public.site_survey_logs ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.has_site_survey_permission(_user_id uuid, _permission text)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.user_app_access uaa
    JOIN public.user_access_profiles uap ON uap.user_id = uaa.user_id
    LEFT JOIN public.access_profile_definitions apd ON apd.code = uap.profile_definition_id
    WHERE uaa.user_id = _user_id
      AND uaa.app_key = 'site_survey'
      AND (
        apd.base_profile = 'admin'
        OR (
          uap.is_customized = true
          AND EXISTS (
            SELECT 1 FROM public.user_menu_permissions ump
            WHERE ump.user_id = _user_id AND ump.menu_key = _permission AND ump.allowed = true
          )
        )
        OR (
          uap.is_customized = false
          AND EXISTS (
            SELECT 1 FROM public.access_profile_permissions app
            WHERE app.profile_code = uap.profile_definition_id AND app.menu_key = _permission AND app.allowed = true
          )
        )
      )
  )
$$;
REVOKE ALL ON FUNCTION public.has_site_survey_permission(uuid, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.has_site_survey_permission(uuid, text) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.can_view_site_survey_visit(_visit_id uuid, _user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.site_survey_visits v
    WHERE v.id = _visit_id
      AND (
        public.has_site_survey_permission(_user_id, 'site_survey_visitas_todas')
        OR (
          public.has_site_survey_permission(_user_id, 'site_survey_visitas_minhas')
          AND (v.technician_id = _user_id OR v.created_by = _user_id)
        )
      )
  )
$$;
REVOKE ALL ON FUNCTION public.can_view_site_survey_visit(uuid, uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.can_view_site_survey_visit(uuid, uuid) TO authenticated, service_role;

CREATE POLICY "Site Survey templates are readable by app users" ON public.site_survey_templates FOR SELECT TO authenticated USING (public.has_site_survey_permission(auth.uid(), 'site_survey_visitas_minhas') OR public.has_site_survey_permission(auth.uid(), 'site_survey_visitas_todas') OR public.has_site_survey_permission(auth.uid(), 'site_survey_configuracoes'));
CREATE POLICY "Site Survey templates are managed by configurators" ON public.site_survey_templates FOR ALL TO authenticated USING (public.has_site_survey_permission(auth.uid(), 'site_survey_configuracoes')) WITH CHECK (public.has_site_survey_permission(auth.uid(), 'site_survey_configuracoes'));
CREATE POLICY "Site Survey sections are readable by app users" ON public.site_survey_sections FOR SELECT TO authenticated USING (public.has_site_survey_permission(auth.uid(), 'site_survey_visitas_minhas') OR public.has_site_survey_permission(auth.uid(), 'site_survey_visitas_todas') OR public.has_site_survey_permission(auth.uid(), 'site_survey_configuracoes'));
CREATE POLICY "Site Survey sections are managed by configurators" ON public.site_survey_sections FOR ALL TO authenticated USING (public.has_site_survey_permission(auth.uid(), 'site_survey_configuracoes')) WITH CHECK (public.has_site_survey_permission(auth.uid(), 'site_survey_configuracoes'));
CREATE POLICY "Site Survey questions are readable by app users" ON public.site_survey_questions FOR SELECT TO authenticated USING (public.has_site_survey_permission(auth.uid(), 'site_survey_visitas_minhas') OR public.has_site_survey_permission(auth.uid(), 'site_survey_visitas_todas') OR public.has_site_survey_permission(auth.uid(), 'site_survey_configuracoes'));
CREATE POLICY "Site Survey questions are managed by configurators" ON public.site_survey_questions FOR ALL TO authenticated USING (public.has_site_survey_permission(auth.uid(), 'site_survey_configuracoes')) WITH CHECK (public.has_site_survey_permission(auth.uid(), 'site_survey_configuracoes'));
CREATE POLICY "Site Survey visits are visible by scope" ON public.site_survey_visits FOR SELECT TO authenticated USING (public.has_site_survey_permission(auth.uid(), 'site_survey_visitas_todas') OR (public.has_site_survey_permission(auth.uid(), 'site_survey_visitas_minhas') AND (technician_id = auth.uid() OR created_by = auth.uid())));
CREATE POLICY "Site Survey visits can be scheduled" ON public.site_survey_visits FOR INSERT TO authenticated WITH CHECK (public.has_site_survey_permission(auth.uid(), 'site_survey_agendar') AND created_by = auth.uid());
CREATE POLICY "Site Survey visits can be updated" ON public.site_survey_visits FOR UPDATE TO authenticated USING (public.has_site_survey_permission(auth.uid(), 'site_survey_editar') OR (public.has_site_survey_permission(auth.uid(), 'site_survey_executar') AND technician_id = auth.uid()) OR public.has_site_survey_permission(auth.uid(), 'site_survey_revisar')) WITH CHECK (public.has_site_survey_permission(auth.uid(), 'site_survey_editar') OR (public.has_site_survey_permission(auth.uid(), 'site_survey_executar') AND technician_id = auth.uid()) OR public.has_site_survey_permission(auth.uid(), 'site_survey_revisar'));
CREATE POLICY "Site Survey visits can be deleted" ON public.site_survey_visits FOR DELETE TO authenticated USING (public.has_site_survey_permission(auth.uid(), 'site_survey_excluir'));
CREATE POLICY "Site Survey responses are visible with visit" ON public.site_survey_responses FOR SELECT TO authenticated USING (public.can_view_site_survey_visit(visit_id, auth.uid()));
CREATE POLICY "Site Survey responses can be created" ON public.site_survey_responses FOR INSERT TO authenticated WITH CHECK (public.can_view_site_survey_visit(visit_id, auth.uid()) AND public.has_site_survey_permission(auth.uid(), 'site_survey_executar'));
CREATE POLICY "Site Survey responses can be updated" ON public.site_survey_responses FOR UPDATE TO authenticated USING (public.can_view_site_survey_visit(visit_id, auth.uid()) AND public.has_site_survey_permission(auth.uid(), 'site_survey_executar')) WITH CHECK (public.can_view_site_survey_visit(visit_id, auth.uid()) AND public.has_site_survey_permission(auth.uid(), 'site_survey_executar'));
CREATE POLICY "Site Survey responses can be deleted" ON public.site_survey_responses FOR DELETE TO authenticated USING (public.can_view_site_survey_visit(visit_id, auth.uid()) AND public.has_site_survey_permission(auth.uid(), 'site_survey_executar'));
CREATE POLICY "Site Survey attachments are visible with visit" ON public.site_survey_attachments FOR SELECT TO authenticated USING (public.can_view_site_survey_visit(visit_id, auth.uid()));
CREATE POLICY "Site Survey attachments can be created" ON public.site_survey_attachments FOR INSERT TO authenticated WITH CHECK (public.can_view_site_survey_visit(visit_id, auth.uid()) AND uploaded_by = auth.uid() AND public.has_site_survey_permission(auth.uid(), 'site_survey_executar'));
CREATE POLICY "Site Survey attachments can be deleted" ON public.site_survey_attachments FOR DELETE TO authenticated USING (public.can_view_site_survey_visit(visit_id, auth.uid()) AND (uploaded_by = auth.uid() OR public.has_site_survey_permission(auth.uid(), 'site_survey_editar')));
CREATE POLICY "Site Survey logs are visible to authorized users" ON public.site_survey_logs FOR SELECT TO authenticated USING (public.can_view_site_survey_visit(visit_id, auth.uid()) OR public.has_site_survey_permission(auth.uid(), 'site_survey_logs'));

CREATE OR REPLACE FUNCTION public.log_site_survey_visit_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.site_survey_logs (visit_id, actor_id, action, details)
    VALUES (NEW.id, auth.uid(), 'visita_criada', jsonb_build_object('status', NEW.status));
  ELSIF NEW.status IS DISTINCT FROM OLD.status THEN
    INSERT INTO public.site_survey_logs (visit_id, actor_id, action, details)
    VALUES (NEW.id, auth.uid(), 'status_alterado', jsonb_build_object('de', OLD.status, 'para', NEW.status));
  END IF;
  RETURN NEW;
END
$$;
CREATE TRIGGER site_survey_visits_log AFTER INSERT OR UPDATE ON public.site_survey_visits FOR EACH ROW EXECUTE FUNCTION public.log_site_survey_visit_change();
CREATE TRIGGER site_survey_templates_updated_at BEFORE UPDATE ON public.site_survey_templates FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER site_survey_sections_updated_at BEFORE UPDATE ON public.site_survey_sections FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER site_survey_questions_updated_at BEFORE UPDATE ON public.site_survey_questions FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER site_survey_visits_updated_at BEFORE UPDATE ON public.site_survey_visits FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER site_survey_responses_updated_at BEFORE UPDATE ON public.site_survey_responses FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE OR REPLACE FUNCTION public.get_site_survey_users()
RETURNS TABLE(id uuid, full_name text, email text)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT p.id, p.full_name, p.email
  FROM public.profiles p
  JOIN public.user_app_access uaa ON uaa.user_id = p.id AND uaa.app_key = 'site_survey'
  WHERE p.deleted_at IS NULL
    AND (
      public.has_site_survey_permission(auth.uid(), 'site_survey_agendar')
      OR public.has_site_survey_permission(auth.uid(), 'site_survey_editar')
      OR public.has_site_survey_permission(auth.uid(), 'site_survey_perfis')
    )
  ORDER BY p.full_name
$$;
REVOKE ALL ON FUNCTION public.get_site_survey_users() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_site_survey_users() TO authenticated, service_role;

CREATE INDEX site_survey_visits_technician_idx ON public.site_survey_visits (technician_id, scheduled_start);
CREATE INDEX site_survey_visits_project_idx ON public.site_survey_visits (project_id);
CREATE INDEX site_survey_visits_client_idx ON public.site_survey_visits (client_id);
CREATE INDEX site_survey_responses_visit_idx ON public.site_survey_responses (visit_id);
CREATE INDEX site_survey_attachments_visit_idx ON public.site_survey_attachments (visit_id);
CREATE INDEX site_survey_logs_visit_idx ON public.site_survey_logs (visit_id, created_at DESC);