import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Minus, Pencil, Plus, Search, ShieldCheck } from "lucide-react";
import { toast } from "sonner";

import { ConfirmDeleteButton } from "@/components/confirm-delete-button";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { supabase } from "@/integrations/supabase/client";

const PERMISSION_GROUPS = [
  { label: "Visitas", children: [["site_survey_visitas_minhas", "Minhas visitas"], ["site_survey_visitas_todas", "Todas as visitas"], ["site_survey_agendar", "Criar e agendar"], ["site_survey_editar", "Editar agendamentos"], ["site_survey_executar", "Executar e preencher"], ["site_survey_revisar", "Revisar e reabrir"], ["site_survey_excluir", "Excluir visitas"]] },
  { label: "Checklists", children: [["site_survey_configuracoes", "Modelos de checklist"]] },
  { label: "Cadastro", children: [["site_survey_cadastro", "Cadastro e Diversos"]] },
  { label: "Usuários", children: [["site_survey_usuarios", "Usuários"], ["site_survey_perfis", "Perfis de acesso"], ["site_survey_logs", "Logs"]] },
] as const;
const ALL_PERMISSIONS = PERMISSION_GROUPS.flatMap((group) => group.children);

type Definition = { code: string; name: string; active: boolean; is_system: boolean; permissions: Set<string> };
type UserAccess = { id: string; full_name: string; email: string | null; profileCode: string; profileName: string; permissions: Set<string>; profilePermissions: Set<string>; customized: boolean };

function PermissionSelector({ value, onChange, disabled = false }: { value: Set<string>; onChange: (next: Set<string>) => void; disabled?: boolean }) {
  const toggle = (key: string, checked: boolean) => { const next = new Set(value); checked ? next.add(key) : next.delete(key); onChange(next); };
  return <div className="grid gap-x-8 gap-y-5 sm:grid-cols-2 lg:grid-cols-3">{PERMISSION_GROUPS.map((group) => { const count = group.children.filter(([key]) => value.has(key)).length; return <div key={group.label} className="space-y-2"><label className="flex items-center gap-2 text-sm font-semibold"><Checkbox disabled={disabled} checked={count === group.children.length ? true : count > 0 ? "indeterminate" : false} onCheckedChange={(checked) => { const next = new Set(value); group.children.forEach(([key]) => checked === true ? next.add(key) : next.delete(key)); onChange(next); }} />{group.label}</label><div className="grid gap-2 border-l border-border pl-4">{group.children.map(([key, label]) => <label key={key} className="flex items-center gap-2 text-sm text-muted-foreground"><Checkbox disabled={disabled} checked={value.has(key)} onCheckedChange={(checked) => toggle(key, checked === true)} />{label}</label>)}</div></div>; })}</div>;
}

function ProfileDialog({ definition, onSaved }: { definition?: Definition; onSaved: () => void }) {
  const [open, setOpen] = useState(false); const [name, setName] = useState(definition?.name ?? ""); const [permissions, setPermissions] = useState(new Set(definition?.permissions ?? [])); const [saving, setSaving] = useState(false);
  const save = async () => { const cleanName = name.trim(); if (cleanName.length < 2) return toast.error("Informe um nome válido."); setSaving(true); const code = definition?.code ?? cleanName.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, ""); const { error } = await supabase.from("site_survey_access_profiles").upsert({ code, name: cleanName, active: true }); if (!error) { const cleared = await supabase.from("site_survey_profile_permissions").delete().eq("profile_code", code); if (!cleared.error && permissions.size) await supabase.from("site_survey_profile_permissions").insert([...permissions].map((permission_key) => ({ profile_code: code, permission_key, allowed: true }))); } setSaving(false); if (error) return toast.error(error.message); toast.success(definition ? "Perfil atualizado" : "Perfil criado"); setOpen(false); onSaved(); };
  return <Dialog open={open} onOpenChange={(next) => { setOpen(next); if (next) { setName(definition?.name ?? ""); setPermissions(new Set(definition?.permissions ?? [])); } }}><DialogTrigger asChild><Button size="compactIcon" variant={definition ? "ghost" : "default"} aria-label={definition ? `Editar ${definition.name}` : "Novo perfil"} title={definition ? "Editar" : "Novo perfil"}>{definition ? <Pencil className="h-3.5 w-3.5" /> : <Plus className="h-3.5 w-3.5" />}</Button></DialogTrigger><DialogContent className="max-h-[90vh] max-w-4xl overflow-y-auto"><DialogHeader><DialogTitle>{definition ? "Editar perfil de acesso" : "Novo perfil de acesso"}</DialogTitle><DialogDescription>Escolha os menus e submenus permitidos.</DialogDescription></DialogHeader><div className="space-y-5"><div className="space-y-2"><Label>Nome</Label><Input value={name} onChange={(event) => setName(event.target.value)} /></div><PermissionSelector value={permissions} onChange={setPermissions} /></div><DialogFooter><Button disabled={saving} onClick={save}>Salvar perfil</Button></DialogFooter></DialogContent></Dialog>;
}

export function SiteSurveyProfilesAdmin() {
  const qc = useQueryClient(); const [filter, setFilter] = useState(""); const [expanded, setExpanded] = useState<string | null>(null);
  const { data, isLoading } = useQuery({ queryKey: ["site-survey-profile-management"], queryFn: async () => { const [{ data: definitions, error }, { data: profilePermissions }, { data: accesses }, { data: profiles }, { data: userProfiles }, { data: userPermissions }] = await Promise.all([supabase.from("site_survey_access_profiles").select("code,name,active,is_system").order("name"), supabase.from("site_survey_profile_permissions").select("profile_code,permission_key,allowed").eq("allowed", true), supabase.from("user_app_access").select("user_id").eq("app_key", "site_survey"), supabase.from("profiles").select("id,full_name,email").is("deleted_at", null).order("full_name"), supabase.from("site_survey_user_profiles").select("user_id,profile_code,is_customized"), supabase.from("site_survey_user_permissions").select("user_id,permission_key,allowed").eq("allowed", true)]); if (error) throw error; const defs = (definitions ?? []).map((item) => ({ ...item, permissions: new Set((profilePermissions ?? []).filter((permission) => permission.profile_code === item.code).map((permission) => permission.permission_key)) })) as Definition[]; const defMap = new Map(defs.map((item) => [item.code, item])); const userProfileMap = new Map((userProfiles ?? []).map((item) => [item.user_id, item])); const allowedIds = new Set((accesses ?? []).map((item) => item.user_id)); const users = (profiles ?? []).filter((profile) => allowedIds.has(profile.id)).map((profile) => { const assigned = userProfileMap.get(profile.id); const definition = defMap.get(assigned?.profile_code ?? "tecnico"); const individual = new Set((userPermissions ?? []).filter((permission) => permission.user_id === profile.id).map((permission) => permission.permission_key)); return { ...profile, profileCode: definition?.code ?? "tecnico", profileName: definition?.name ?? "Técnico", profilePermissions: new Set(definition?.permissions ?? []), permissions: assigned?.is_customized ? individual : new Set(definition?.permissions ?? []), customized: Boolean(assigned?.is_customized) } as UserAccess; }); return { definitions: defs, users }; } });
  const invalidate = () => { qc.invalidateQueries({ queryKey: ["site-survey-profile-management"] }); qc.invalidateQueries({ queryKey: ["site-survey-data"] }); qc.invalidateQueries({ queryKey: ["site-survey-users-admin"] }); };
  const toggle = async (definition: Definition, active: boolean) => { const { error } = await supabase.from("site_survey_access_profiles").update({ active }).eq("code", definition.code); if (error) return toast.error(error.message); invalidate(); };
  const remove = async (definition: Definition) => { const { error } = await supabase.from("site_survey_access_profiles").update({ active: false }).eq("code", definition.code); if (error) return toast.error(error.message); toast.success("Perfil excluído"); invalidate(); };
  const saveUser = async (user: UserAccess, permissions: Set<string>) => { const customized = ALL_PERMISSIONS.some(([key]) => permissions.has(key) !== user.profilePermissions.has(key)); const cleared = await supabase.from("site_survey_user_permissions").delete().eq("user_id", user.id); if (cleared.error) return toast.error(cleared.error.message); if (customized && permissions.size) { const inserted = await supabase.from("site_survey_user_permissions").insert([...permissions].map((permission_key) => ({ user_id: user.id, permission_key, allowed: true }))); if (inserted.error) return toast.error(inserted.error.message); } const updated = await supabase.from("site_survey_user_profiles").upsert({ user_id: user.id, profile_code: user.profileCode, is_customized: customized }); if (updated.error) return toast.error(updated.error.message); toast.success("Acesso customizado atualizado"); invalidate(); };
  const normalized = filter.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase(); const users = (data?.users ?? []).filter((user) => (user.full_name || user.email || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().includes(normalized));
  return <div className="space-y-6"><Card><CardHeader className="flex flex-row items-start justify-between gap-4"><div><CardTitle>Perfis cadastrados</CardTitle><CardDescription>Crie perfis reutilizáveis escolhendo os menus e submenus permitidos.</CardDescription></div><ProfileDialog onSaved={invalidate} /></CardHeader><CardContent>{isLoading ? <p className="text-sm text-muted-foreground">Carregando...</p> : <Table><TableHeader><TableRow><TableHead>Nome</TableHead><TableHead>Acessos</TableHead><TableHead>Ativo</TableHead><TableHead aria-label="Ações" /></TableRow></TableHeader><TableBody>{data?.definitions.map((definition) => <TableRow key={definition.code}><TableCell className="font-medium">{definition.name}</TableCell><TableCell>{definition.permissions.size === ALL_PERMISSIONS.length ? "Todos" : `${definition.permissions.size} selecionados`}</TableCell><TableCell><Switch checked={definition.active} onCheckedChange={(active) => void toggle(definition, active)} /></TableCell><TableCell><div className="flex justify-end gap-1"><ProfileDialog definition={definition} onSaved={invalidate} /><ConfirmDeleteButton title={`Excluir ${definition.name}?`} description="O perfil deixará de aparecer para novas atribuições. Os usuários vinculados manterão o registro atual." onConfirm={() => void remove(definition)} /></div></TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="h-5 w-5" />Customizar acessos de perfis pré-definidos</CardTitle><CardDescription>Adicione ou remova acessos do perfil atual de cada usuário.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="relative max-w-sm"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={filter} onChange={(event) => setFilter(event.target.value)} placeholder="Filtrar por nome do usuário" className="pl-9" /></div>{users.map((user) => <UserCustomization key={user.id} user={user} open={expanded === user.id} onToggle={() => setExpanded((current) => current === user.id ? null : user.id)} onSave={saveUser} />)}</CardContent></Card></div>;
}

function UserCustomization({ user, open, onToggle, onSave }: { user: UserAccess; open: boolean; onToggle: () => void; onSave: (user: UserAccess, permissions: Set<string>) => Promise<void> }) {
  const [permissions, setPermissions] = useState(new Set(user.permissions));
  return <div className="rounded-md border border-border"><div className="flex items-center gap-3 p-3"><Button size="compactIcon" variant="ghost" onClick={onToggle} aria-label={open ? `Recolher ${user.full_name}` : `Exibir ${user.full_name}`}>{open ? <Minus className="h-3.5 w-3.5" /> : <Plus className="h-3.5 w-3.5" />}</Button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="truncate text-sm font-medium">{user.full_name || "—"}</p><Badge variant="outline">{user.profileName}</Badge>{user.customized ? <Badge>Acesso customizado</Badge> : null}</div><p className="truncate text-xs text-muted-foreground">{user.email}</p></div></div>{open ? <div className="space-y-4 border-t border-border p-3"><PermissionSelector value={permissions} onChange={setPermissions} /><div className="flex justify-end"><Button onClick={() => void onSave(user, permissions)}>Salvar customização</Button></div></div> : null}</div>;
}